// Generated by CoffeeScript 1.10.0
var CHAT_FILE_PATH, INTERVAL_SEC, LOG_NUM, VIDEO_ID, args, dateStr, datetimeStr, page, repeat, system, zerofill;

VIDEO_ID = null;

LOG_NUM = 500;

INTERVAL_SEC = 1;

CHAT_FILE_PATH = 'chat.log';

system = require('system');

args = system.args;

if (args.length >= 2) {
  VIDEO_ID = args[1];
}

if (args.length >= 3) {
  LOG_NUM = args[2];
}

if (args.length >= 4) {
  INTERVAL_SEC = args[3];
}

VIDEO_ID = VIDEO_ID.replace(/^https\:\/\/www\.youtube\.com\/watch\?v\=/, '');

page = require('webpage').create();

page.open('https://www.youtube.com/live_chat?is_popout=1&v=' + VIDEO_ID, function() {
  return page.includeJs('http://code.jquery.com/jquery-1.12.4.min.js', function() {
    var func;
    func = function() {
      var error, fileBuf, fs, i, len, r, res;
      res = page.evaluate(function() {
        var comment, comments, date, dateStr, datetimeStr, elem, hash, i, len, name, nowMs, ref, repeat, zerofill;
        dateStr = function(date, dateSep) {
          if (date == null) {
            date = null;
          }
          if (dateSep == null) {
            dateSep = '-';
          }
          if (date === null) {
            date = new Date();
          }
          return '' + zerofill(date.getFullYear(), 4) + dateSep + zerofill(date.getMonth() + 1, 2) + dateSep + zerofill(date.getDate(), 2);
        };
        datetimeStr = function(date, dateSep, timeSep, betweenSep) {
          if (date == null) {
            date = null;
          }
          if (dateSep == null) {
            dateSep = '-';
          }
          if (timeSep == null) {
            timeSep = ':';
          }
          if (betweenSep == null) {
            betweenSep = ' ';
          }
          if (date === null) {
            date = new Date();
          }
          return dateStr(date, dateSep) + betweenSep + zerofill(date.getHours(), 2) + timeSep + zerofill(date.getMinutes(), 2) + timeSep + zerofill(date.getSeconds(), 2);
        };
        zerofill = function(num, digit) {
          return ('' + repeat('0', digit) + num).slice(-digit);
        };
        repeat = function(str, times) {
          return Array(1 + times).join(str);
        };
        comments = [];
        ref = $('#all-comments li');
        for (i = 0, len = ref.length; i < len; i++) {
          elem = ref[i];
          nowMs = $(elem).data('timestamp');
          date = datetimeStr(new Date(1000 * nowMs));
          name = $(elem).find('.yt-user-name').eq(0).html();
          name = name.replace(/\t/g, ' ');
          name = name.replace(/<span[^>]*?>.*?<\/span>/g, '');
          name = name.replace(/[\r\n]/g, '');
          name = name.replace(/^\s+/, '');
          name = name.replace(/\s+$/, '');
          comment = $(elem).find('.comment-text').eq(0).html();
          comment = comment.replace(/\t/g, ' ');
          comment = comment.replace(/<span[^>]*?>.*?<\/span>/g, '');
          comment = comment.replace(/[\r\n]/g, '');
          comment = comment.replace(/^\s+/, '');
          comment = comment.replace(/\s+$/, '');
          if (comment !== '') {
            hash = {
              date: date,
              name: name,
              comment: comment
            };
            comments.push(hash);
          }
        }
        return comments;
      });
      res = res.slice(LOG_NUM * (-1));
      fileBuf = '';
      for (i = 0, len = res.length; i < len; i++) {
        r = res[i];
        fileBuf += r.date + "\t" + r.name + "\t" + r.comment + "\n";
      }
      fs = require('fs');
      try {
        fs.write(CHAT_FILE_PATH, fileBuf, 'w');
        console.log('wrote:' + datetimeStr());
      } catch (error) {
        console.log('wrote fail:' + datetimeStr());
      }
      return setTimeout(func, INTERVAL_SEC * 1000);
    };
    return func();
  });
});

dateStr = function(date, dateSep) {
  if (date == null) {
    date = null;
  }
  if (dateSep == null) {
    dateSep = '-';
  }
  if (date === null) {
    date = new Date();
  }
  return '' + zerofill(date.getFullYear(), 4) + dateSep + zerofill(date.getMonth() + 1, 2) + dateSep + zerofill(date.getDate(), 2);
};

datetimeStr = function(date, dateSep, timeSep, betweenSep) {
  if (date == null) {
    date = null;
  }
  if (dateSep == null) {
    dateSep = '-';
  }
  if (timeSep == null) {
    timeSep = ':';
  }
  if (betweenSep == null) {
    betweenSep = ' ';
  }
  if (date === null) {
    date = new Date();
  }
  return dateStr(date, dateSep) + betweenSep + zerofill(date.getHours(), 2) + timeSep + zerofill(date.getMinutes(), 2) + timeSep + zerofill(date.getSeconds(), 2);
};

zerofill = function(num, digit) {
  return ('' + repeat('0', digit) + num).slice(-digit);
};

repeat = function(str, times) {
  return Array(1 + times).join(str);
};
